### ISSUE TITLE
free-outernet.py exits when decoding - FEC block already received message

### ISSUE THREAD

**Issue by Arander** [daniestevez/free-outernet#5]
When running free-outernet.py , the script ends before attempting to recover files, with the message "FEC block already received!". I traced the cause to line 201 of files.py :

201   raise ValueError('File.push_fec(): FEC block already received!')

Is this normal behaviour? I replaced 'raise ValueError' with 'print' and while I got quite a few "FEC block already received!" messages, the script continues and decodes other files.

Sorry for any mistakes, my first comment in GirHub...just an enthusiastic HAM operator here.

**Comment by daniestevez** [comment]
This seems to be a bug. It is not normal behaviour, but I guess it could happen under some special conditions involving some lost packets.

Do you have or can make a KISS recording that would produce this problem? It will help me to sort this out.

**Comment by Arander** [comment]
Thank you for the answer, Dani. Here's a KISS file example
[FEC-exit.kiss.zip](https://github.com/daniestevez/free-outernet/files/796885/FEC-exit.kiss.zip)

When running the script, I get some files decoded but it then exits with the following lines:

[Time service] Server ID: odc2
[Time service] Server time: 2017-02-22 08:50:57 UTC
[File service] File reconstructed: opaks/4232-news-pack.2017-02-22_0843.tbz2
Traceback (most recent call last):
  File "free-outernet.py", line 167, in <module> 
    main()
  File "free-outernet.py", line 155, in main
    processFrame(frame)
  File "free-outernet.py", line 74, in processFrame
    router.route(packet)
  File "/home/andres/free-outernet/protocols.py", line 241, in route
    self.__registrations[packet.type](packet)
  File "/home/andres/free-outernet/files.py", line 119, in __fec_packet
    f.push_fec(block, block_number)
  File "/home/andres/free-outernet/files.py", line 201, in push_fec
    raise ValueError('File.push_fec(): FEC block already received!')
ValueError: File.push_fec(): FEC block already received!

**Comment by daniestevez** [comment]
Thanks for the KISS recording. I have just used it to check and fix this bug.
