### ISSUE TITLE
No module named zfec

### ISSUE THREAD

**Issue by lccreech** [daniestevez/free-outernet#6]
Ubuntu 16.04 errors out:
 ./free-outernet.py 
Traceback (most recent call last):
  File "./free-outernet.py", line 22, in <module>
    import protocols
  File "/home/larry/Downloads/free-outernet/protocols.py", line 29, in <module>
    import zfec
ImportError: No module named 'zfec'

It has been installed:
sudo pip install -r requirements.txt
The directory '/home/larry/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/larry/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: crcmod<2,>=1.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pyutil from git+https://github.com/george-hopkins/pyutil@python3#egg=pyutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: zfec from git+https://github.com/george-hopkins/zfec@python3#egg=zfec in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))

**Comment by daniestevez** [comment]
You are using `pip` from Python 2. You should use `pip3` instead.

**Comment by lccreech** [comment]
Daniel,

Thanks! That solved that issue. Now how do you run it? I don't get any
output. I've tried:

larry@Dell:~/Downloads/free-outernet$ ./free-outernet.py  <
/tmp/outernet.kiss
^C
larry@Dell:~/Downloads/free-outernet$ ./free-outernet.py
^C
larry@Dell:~/Downloads/free-outernet$ cat /tmp/outernet.kiss |
./free-outernet.py
^C

larry@Dell:~/Downloads/free-outernet$ ls -al /tmp/outernet.kiss
-rw-rw-r-- 1 larry larry 1625453 Mar 17 22:25 /tmp/outernet.kiss

**Comment by daniestevez** [comment]
Run it as `./free-outernet.py -k /tmp/outernet.kiss`. You can use `-h` to get a list of command line options.

**Comment by lccreech** [comment]
Thanks,
I was just about to email you. I figured it out after reading the code

**Comment by lccreech** [comment]
Nice work! I was going to do the same when I found your stuff. Is the
hangup fixed yet for the decode in gnuradio? I'm experiencing the same
problem as the open issue. I can record the raw IQ data or anything else if
you need samples.

Thanks,
Larry Creech

**Comment by daniestevez** [comment]
The hangup seems to be some odd and subtle problem with GNU Radio. I've tried to replicate it in my system, but I've been unable so far. Another user managed to do some recordings that would trigger the hangup when played back in his system. In my system they would play back normally using the same flowgraph.

If you want to make recordings, I can play them back in my system to see if I can replicate the hangup, but I can't promise much more.
